// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef TESTCPP_TEST_H
#define TESTCPP_TEST_H

/************************************************************
 Test class header
 ************************************************************/

#include "TestCpp/Pkg_TestCpp.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"

// Include from Include stereotype (header)
#include "string"
#include "iostream"
// End of Include stereotype (header)

namespace TestCpp {

/************************************************************/
/**
 * 
 */
class Test {
public:

	/**
	 * **********************************************************
	 *  Test class body
	 *  ***********************************************************
	 * 
	 * // include associated header file
	 * #include "TespCppReverse/Test.h"
	 * 
	 * // Derived includes directives
	 * 
	 * // Include from Include declaration (body)
	 */
	Test();

	/**
	 * 
	 * @param number 
	 */
	void setNum(int /*in*/number);

	/**
	 * @return ret
	 * @param a 
	 * @param b 
	 */
	int add(int /*in*/a, int /*in*/b);

private:

	/**
	 * 
	 */
	int num;

	/**
	 * 
	 */
	std::string name;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace TestCpp

/************************************************************
 End of Test class header
 ************************************************************/

#endif
