// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define TestOrigin_Test_BODY

/************************************************************
 Test class body
 ************************************************************/

// include associated header file
#include "TestOrigin/Test.h"

// Derived includes directives

namespace TestOrigin {

// static attributes (if any)
/**
 * 
 */
int Test::cnt = 0;

/**
 * 
 */
Test::Test() :
		id(0), name("default name") {

	cnt++;
	run();
}

/**
 * 
 */
Test::~Test() {

	std::cout << "Destructor called" << std::endl;
}

/**
 * 
 * @param id 
 */
void Test::setId(const int /*in*/id) {

	this->id = id;
}

/**
 * 
 * @param name 
 */
void Test::setName(const std::string & /*in*/name) {

	this->name = name;
}

/**
 * 
 * @return ret 
 */
int Test::getId() const {

	return id;
}

/**
 * 
 * @return ret 
 */
std::string Test::getName() const {

	std::cout << "getName() called..." << std::endl;
	return name;
}

/**
 * 
 */
void Test::run() {

	std::cout << "run running..." << std::endl;
	std::cout << "id: " << getId() << std::endl;
	std::cout << "name: " << getName() << std::endl;
}

} // of namespace TestOrigin

/************************************************************
 End of Test class body
 ************************************************************/
