// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef TESTORIGIN_TEST_H
#define TESTORIGIN_TEST_H

/************************************************************
 Test class header
 ************************************************************/

#include "TestOrigin/Pkg_TestOrigin.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"

// Include from Include stereotype (header)
#include "iostream"
// End of Include stereotype (header)

namespace TestOrigin {

/************************************************************/
/**
 * 
 */
class Test {
public:

	/**
	 * 
	 */
	Test();

	/**
	 * 
	 */
	virtual ~Test();

	/**
	 * 
	 * @param id 
	 */
	void setId(const int /*in*/id);

	/**
	 * 
	 * @param name 
	 */
	void setName(const std::string & /*in*/name);

	/**
	 * 
	 * @return ret 
	 */
	int getId() const;

	/**
	 * 
	 * @return ret 
	 */
	std::string getName() const;

	/**
	 * 
	 */
	void run();

private:

	/**
	 * 
	 */
	int id;

	/**
	 * 
	 */
	std::string name;

	/**
	 * 
	 */
	static int cnt;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace TestOrigin

/************************************************************
 End of Test class header
 ************************************************************/

#endif
