// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef TESTORIGIN_TESTORIGIN_H
#define TESTORIGIN_TESTORIGIN_H

/************************************************************
 TestOrigin class header
 ************************************************************/

#include "TestOrigin/Pkg_TestOrigin.h"

// Include from Include stereotype (header)
#include "TestOrigin/Pkg_TestOrigin.h"
#include "iostream"
#include "Test.h"
// End of Include stereotype (header)

namespace TestOrigin {

/************************************************************/
/**
 * 
 */
class TestOrigin {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace TestOrigin

/************************************************************
 End of TestOrigin class header
 ************************************************************/

#endif
