// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define TestOrigin_TestOrigin_BODY

/************************************************************
 TestOrigin class body
 ************************************************************/

// include associated header file
#include "TestOrigin/TestOrigin.h"

// Derived includes directives

// Include from Include declaration (body)
int main() {
	std::cout << "Test Origin\n" << std::endl; // prints Title\n
	TestOrigin::Test t;
	t.run();
	TestOrigin::Test t2;
	t2.run();
	return 0;
}
// End of Include declaration (body)

namespace TestOrigin {

// static attributes (if any)

}// of namespace TestOrigin

/************************************************************
 End of TestOrigin class body
 ************************************************************/
