// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef TESTORIGIN_MYSTRUCTURE_H
#define TESTORIGIN_MYSTRUCTURE_H

/************************************************************
 MyStructure class header
 ************************************************************/

#include "TestOrigin/Pkg_TestOrigin.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"

namespace TestOrigin
{

/************************************************************/
/**
 * 
 */
struct MyStructure
{

	/**
	 * 
	 */
	int element;

	/**
	 * 
	 */
	char project[10];

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace TestOrigin

/************************************************************
 End of MyStructure class header
 ************************************************************/

#endif
