// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define TestCpp_Test_BODY

/************************************************************
 Test class body
 ************************************************************/

// include associated header file
#include "TestCpp/Test.h"

// Derived includes directives

// Include from Include declaration (body)
int main() {
	TestCpp::Test test;
	return 0;
}
// End of Include declaration (body)

namespace TestCpp {

// static attributes (if any)

/**
 * **********************************************************
 *  Test class body
 *  ***********************************************************
 * 
 * // include associated header file
 * #include "TespCppReverse/Test.h"
 * 
 * // Derived includes directives
 * 
 * // Include from Include declaration (body)
 */
Test::Test() :
		num(0) {

	setNum(2);
	std::cout << "add 2+2= " << add(num, num) << std::endl;
}

/**
 * 
 * @param number 
 */
void Test::setNum(int /*in*/number) {

	num = number;
}

/**
 * @return ret
 * @param a 
 * @param b 
 */
int Test::add(int /*in*/a, int /*in*/b) {

	return a + b;
}

} // of namespace TestCpp

/************************************************************
 End of Test class body
 ************************************************************/
